### ISSUE TITLE
[Bug] 이미지 캐러셀에서 이미지 선택 도트 표시가 이상해요!

### ISSUE THREAD

**Issue by superLipbalm** [boostcampwm-2021/web14-salondesrefuses#114]
## 📃 이슈 내용

이미지 캐러셀에서 하단의 도트를 눌러 선택하면 흘러가는 진한 도트와 선택한 진한 도트 두개가 남아요!
그리고 독전 페이지 디자인 너무 예뻐요! 잘보고 갑니다!

## 스크린샷

![버그버그](https://user-images.githubusercontent.com/77329061/140334720-d82ceaa6-5e7f-4e57-8823-e6a7a9689fb7.gif)

**Comment by Alencion** [comment]
아니 버그도 찾아주신다구요? 감사합니다 ㅋㅋㅋㅋㅋㅋㅋㅋ
