### ISSUE TITLE
[BUG] 작품 추가 페이지 > 내 아트워크 보기 버그

### ISSUE THREAD

**Issue by imnotmoon** [boostcampwm-2021/web14-salondesrefuses#152]
## 📃 버그 내용

userId 6번 계정으로 작품 추가 페이지에 들어갔는데 다른사람 작품이 나와요!

## 스크린샷

![스크린샷 2021-11-10 오후 6 15 10](https://user-images.githubusercontent.com/53335940/141085000-e439637f-cfc8-434a-bc55-2e0fced8a6eb.png)
![스크린샷 2021-11-10 오후 6 17 30](https://user-images.githubusercontent.com/53335940/141085177-013866c1-7037-402e-8a3e-018f80c1726f.png)
작품 올린거 지구사진이랑 다른거 두갠데 저거 다 남의 작품임..

**Comment by imnotmoon** [comment]
API 문제는 아니고 클라이언트가 userId를 안갖고있어서 생긴 문제였습니다.

**Comment by Alencion** [comment]
확인해볼게
