### ISSUE TITLE
(중간)[FE] React Experimental 버전 적용

### ISSUE THREAD

**Issue by imnotmoon** [boostcampwm-2021/web14-salondesrefuses#216]
## 📃 이슈 내용

리액트 v18 실험 버전 적용

## ✅ 체크 리스트

- [ ]  리액트 버전업

## 📌 레퍼런스

[리액트 버전업에 대한 질문](https://stackoverflow.com/questions/63213597/is-it-possible-to-use-experimental-version-of-react-while-using-create-react-app)

**Comment by illlama** [comment]
너무나도 당연하게 오류가 생겼지만 해결하기 힘들어서 next에 issue 올려둠
https://github.com/vercel/next.js/issues/31675
