### ISSUE TITLE
[FIX] exhibiton 엔티티에 artworkIds 를 포함하도록 변경

### ISSUE THREAD

**Issue by Alencion** [boostcampwm-2021/web14-salondesrefuses#228]
## 📃 버그 내용

 exhibiton 엔티티에 artworkIds 를 포함하도록 변경. 
비정규화 했어요. artwork 조인 그만해!!!

**Comment by illlama** [comment]
![image](https://user-images.githubusercontent.com/13018853/142977516-66ece179-8565-408f-93ad-a4af34a2fa04.png)
잘 작동됩니다!!
